import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'daos/exercises_dao.dart';
import 'daos/sessions_dao.dart';
import 'daos/templates_dao.dart';

part 'app_database.g.dart';

// ─────────────────────────────────────────────────────────────────────────────
// Table definitions
// Each column maps directly to the schema in OFFLINE_PLAN.md
// ─────────────────────────────────────────────────────────────────────────────

// ── exercises_cache ───────────────────────────────────────────────────────────
// All 873 exercises fetched from the server and stored locally.
// JSON-encoded array columns (bodyParts, equipments, etc.) are stored as TEXT
// and decoded in the DAO layer — Drift doesn't support array columns natively.
class ExercisesCache extends Table {
  TextColumn get id => text()();
  TextColumn get name => text()();
  TextColumn get category => text().nullable()();
  // JSON-encoded List<String>
  TextColumn get bodyParts => text().withDefault(const Constant('[]'))();
  TextColumn get targetMuscles => text().withDefault(const Constant('[]'))();
  TextColumn get secondaryMuscles => text().withDefault(const Constant('[]'))();
  TextColumn get equipments => text().withDefault(const Constant('[]'))();
  TextColumn get difficulty => text().nullable()();
  TextColumn get gifUrl => text().nullable()();
  // JSON-encoded { small, medium, large } or null
  TextColumn get imageUrls => text().nullable()();
  // JSON-encoded List<String>
  TextColumn get instructions => text().withDefault(const Constant('[]'))();
  TextColumn get overview => text().nullable()();
  BoolColumn get isCustom => boolean().withDefault(const Constant(false))();
  // Unix milliseconds — used to decide when to refresh the cache
  IntColumn get cachedAt => integer()();

  @override
  Set<Column> get primaryKey => {id};
}

// ── workout_templates_cache ───────────────────────────────────────────────────
// System + gym templates cached at login, available offline.
class WorkoutTemplatesCache extends Table {
  TextColumn get id => text()();
  TextColumn get name => text()();
  TextColumn get description => text().nullable()();
  TextColumn get category => text().nullable()();
  TextColumn get difficulty => text().nullable()();
  IntColumn get durationMins => integer().nullable()();
  // 'system' | 'gym' | 'user'
  TextColumn get source => text().withDefault(const Constant('system'))();
  TextColumn get imageUrl => text().nullable()();
  // Full JSON blob of WorkoutTemplateExercise[] including nested exercise data
  TextColumn get exercisesJson => text().withDefault(const Constant('[]'))();
  BoolColumn get isActive => boolean().withDefault(const Constant(true))();
  IntColumn get cachedAt => integer()();

  @override
  Set<Column> get primaryKey => {id};
}

// ── pending_sessions ──────────────────────────────────────────────────────────
// Workout sessions created while offline (or before server confirmation).
// Every session — online or offline — passes through this table first.
// The sync service promotes them to the server and fills in serverId.
class PendingSessions extends Table {
  // Local UUID generated by the app — never changes
  TextColumn get localId => text()();
  // Server UUID — null until successfully synced
  TextColumn get serverId => text().nullable()();
  TextColumn get gymId => text()();
  TextColumn get userId => text()();
  TextColumn get templateId => text().nullable()();
  IntColumn get startedAt => integer()();
  IntColumn get endedAt => integer().nullable()();
  TextColumn get notes => text().nullable()();
  // 'pending' | 'syncing' | 'synced' | 'failed'
  TextColumn get syncStatus => text().withDefault(const Constant('pending'))();
  TextColumn get syncError => text().nullable()();
  IntColumn get retryCount => integer().withDefault(const Constant(0))();
  IntColumn get createdAt => integer()();

  @override
  Set<Column> get primaryKey => {localId};
}

// ── pending_sets ──────────────────────────────────────────────────────────────
// Individual sets logged during a workout.
// Synced to the server after their parent session has a serverId.
class PendingSets extends Table {
  TextColumn get localId => text()();
  TextColumn get serverId => text().nullable()();
  // FK to pending_sessions.localId
  TextColumn get sessionLocalId => text()();
  // Populated once the parent session syncs
  TextColumn get sessionServerId => text().nullable()();
  // Server exercise UUID — always available because exercises are cached
  TextColumn get exerciseId => text()();
  IntColumn get setNumber => integer().nullable()();
  // Strength fields
  IntColumn get reps => integer().nullable()();
  RealColumn get weightKg => real().nullable()();
  RealColumn get rpe => real().nullable()();
  RealColumn get assistKg => real().nullable()();
  // Cardio fields
  IntColumn get durationSecs => integer().nullable()();
  RealColumn get distanceM => real().nullable()();
  RealColumn get speedKph => real().nullable()();
  // Set by server during sync if this is a personal record
  BoolColumn get isPr => boolean().withDefault(const Constant(false))();
  // 'pending' | 'synced' | 'failed'
  TextColumn get syncStatus => text().withDefault(const Constant('pending'))();
  IntColumn get createdAt => integer()();

  @override
  Set<Column> get primaryKey => {localId};
}

// ── queued_workout_shares ─────────────────────────────────────────────────────
// Durable share intents created when a completed workout is offline or has not
// received its server session ID yet.
class QueuedWorkoutShares extends Table {
  TextColumn get id => text()();
  TextColumn get sessionId => text()();
  TextColumn get content => text().nullable()();
  TextColumn get imagePath => text().nullable()();
  IntColumn get createdAt => integer()();

  @override
  Set<Column> get primaryKey => {id};
}

// ── recently_used_cache ───────────────────────────────────────────────────────
// Locally tracked recently used exercises — mirrors the server table but
// works fully offline. One row per exercise per user.
class RecentlyUsedCache extends Table {
  // exercise_id is the PK — one row per exercise
  TextColumn get exerciseId => text()();
  TextColumn get userId => text()();
  IntColumn get usedAt => integer()();
  IntColumn get useCount => integer().withDefault(const Constant(1))();

  @override
  Set<Column> get primaryKey => {exerciseId, userId};
}

// ─────────────────────────────────────────────────────────────────────────────
// AppDatabase
// ─────────────────────────────────────────────────────────────────────────────
@DriftDatabase(
  tables: [
    ExercisesCache,
    WorkoutTemplatesCache,
    PendingSessions,
    PendingSets,
    QueuedWorkoutShares,
    RecentlyUsedCache,
  ],
  daos: [ExercisesDao, SessionsDao, TemplatesDao],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  // Increment schemaVersion whenever a table definition changes.
  // Add a migration step in onUpgrade below.
  @override
  int get schemaVersion => 4;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (m) => m.createAll(),
    onUpgrade: (m, from, to) async {
      // Future migrations go here, e.g.:
      // if (from < 2) await m.addColumn(pendingSessions, pendingSessions.notes);
      if (from < 2) {
        await m.createTable(queuedWorkoutShares);
      }
      if (from < 3) {
        await m.addColumn(pendingSessions, pendingSessions.templateId);
      }
      if (from < 4) {
        await m.addColumn(queuedWorkoutShares, queuedWorkoutShares.imagePath);
      }
    },
  );
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    return driftDatabase(name: 'tether_offline.db');
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// Riverpod provider
// ─────────────────────────────────────────────────────────────────────────────
final appDatabaseProvider = Provider<AppDatabase>((ref) {
  final db = AppDatabase();
  // Close the database when the provider is disposed (app shutdown)
  ref.onDispose(db.close);
  return db;
});
